name: Deploy Python App to EC2
on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:   # ✅ Manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      # till here we have setup the ssh key and added the host to known hosts on ubuntu agent
    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          mkdir -p /home/ec2-user/app 
          cd /home/ec2-user/app
          sudo yum install git -y
          git clone https://github.com/sagsrinu/python-app.git 
          cd /home/ec2-user/app/python-app
          git pull origin main
          sudo yum install python3-pip -y
          pip freeze > requirements.txt
          pip3 install -r requirements.txt
          pkill -f app.py || true
          nohup python3 app.py > output.log 2>&1 &
        EOF
